# ====================[ kitty/userprefs.conf               ]====================
#
# --------------------( LICENSE                            )--------------------
# Copyright 2025-2026 by Cecil Curry.
# See "LICENSE" for further details.
#
# --------------------( SYNOPSIS                           )--------------------
# Kitty-specific terminal configuration.
#
# --------------------( BINDINGS                           )--------------------
# Kitty ships with a number of non-standard (albeit useful) key bindings,
# including:
# * <Ctrl-Shift + h>, invoke a pager (e.g., "less", "more") over the current
#   Kitty terminal scroll buffer. Since searching inside a pager is trivial via
#   the standard </> key binding, Kitty buffers are effectively searchable
#   out-of-the-box by typing <Ctrl-Shift + h, />. Although this is admittedly a
#   bit of a mouthful and could be reduced with a custom key binding, doing so
#   would be more trouble than it's worth. Since we only rarely perform buffer
#   searches, the default key bindings suffice (and also generalize to other
#   systems lacking this custom configuration). See also this upstream issue:
#   https://github.com/kovidgoyal/kitty/issues/718

# ....................{ INCLUDE                            }....................
include hyde.conf

# ....................{ CURSOR                             }....................
# Disable cursor blink (i.e., prevent the cursor from blinking, ever).
cursor_blink_interval 0
# cursor_stop_blinking_after 0  # <-- does nothing lol

# ....................{ FONT                               }....................
# Increase the default font size so we no longer have to go blind.
font_size 12.0

# ....................{ KEYS                               }....................
# remap to open new kitty tab in the same directory (default is home dir)
# map ctrl+shift+t            new_tab_with_cwd

# ....................{ SPEED                              }....................
# Uncomment the following 4 lines to minimize kitty latency (higher energy usage)
# input_delay 0
# repaint_delay 2
# sync_to_monitor no
# wayland_enable_ime no

# ....................{ TAB                                }....................
# Minimal Tab bar styling.
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# ....................{ WINDOW                             }....................
# Decrease the window padding width (i.e., the number of dead pixels bordering
# the internal edges of Kitty windows).
window_padding_width 5
